### ISSUE TITLE
Get rid of RenderScript

### ISSUE THREAD

**Issue by KOLANICH** [markusfisch/BinaryEye#78]

**Comment by markusfisch** [comment]
Why?

**Comment by KOLANICH** [comment]
1. It seem to be used only for screen rotation.
2. it carries native libraries
3. It doesn't work well on my device.

<details>
<summary>logcat</summary>

```
--------- beginning of /dev/log/main
D/su      ( 3115): 0 /system/bin/mksh executing 10139 logcat using binary /system/bin/sh : sh -c logcat
W/XPrivacy( 3123): Hooking package=de.markusfisch.android.binaryeye
D/ActivityThread( 3123): handleBindApplication:de.markusfisch.android.binaryeye
D/ActivityThread( 3123): setTargetHeapUtilization:0.75
D/ActivityThread( 3123): setTargetHeapMinFree:2097152
I/dalvikvm( 3123): Could not find method android.view.Window$Callback.onProvideKeyboardShortcuts, referenced from method a.a.d.g.i.onProvideKeyboardShortcuts
W/dalvikvm( 3123): VFY: unable to resolve interface method 9844: Landroid/view/Window$Callback;.onProvideKeyboardShortcuts (Ljava/util/List;Landroid/view/Menu;I)V
D/dalvikvm( 3123): VFY: replacing opcode 0x72 at 0x0002
W/dalvikvm( 3123): VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
I/dalvikvm( 3123): Could not find method android.view.Window$Callback.onSearchRequested, referenced from method a.a.d.g.i.onSearchRequested
W/dalvikvm( 3123): VFY: unable to resolve interface method 9846: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
D/dalvikvm( 3123): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm( 3123): Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method a.a.d.g.i.onWindowStartingActionMode
W/dalvikvm( 3123): VFY: unable to resolve interface method 9850: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
D/dalvikvm( 3123): VFY: replacing opcode 0x72 at 0x0002
I/dalvikvm( 3123): DexOpt: illegal method access (call Landroid/content/res/TypedArray;.<init> (Landroid/content/res/Resources;[I[II)V from Landroid/content/res/XResources$XTypedArray;)
I/dalvikvm( 3123): Could not find method android.content.res.TypedArray.<init>, referenced from method android.content.res.XResources$XTypedArray.<init>
W/dalvikvm( 3123): VFY: unable to resolve direct method 82: Landroid/content/res/TypedArray;.<init> (Landroid/content/res/Resources;[I[II)V
D/dalvikvm( 3123): VFY: replacing opcode 0x70 at 0x0002
I/Timeline( 3123): Timeline: Activity_launch_request id:de.markusfisch.android.binaryeye time:296033782
I/dalvikvm( 3123): Could not find method android.content.Context.getColorStateList, referenced from method a.a.d.b.a.b.b
W/dalvikvm( 3123): VFY: unable to resolve virtual method 2727: Landroid/content/Context;.getColorStateList (I)Landroid/content/res/ColorStateList;
D/dalvikvm( 3123): VFY: replacing opcode 0x6e at 0x0006
E/dalvikvm( 3123): Could not find class 'android.graphics.drawable.RippleDrawable', referenced from method android.support.v7.widget.o.a
W/dalvikvm( 3123): VFY: unable to resolve instanceof 501 (Landroid/graphics/drawable/RippleDrawable;) in Landroid/support/v7/widget/o;
D/dalvikvm( 3123): VFY: replacing opcode 0x20 at 0x000c
I/dalvikvm( 3123): Could not find method android.view.Window.setStatusBarColor, referenced from method de.markusfisch.android.binaryeye.app.l.a
W/dalvikvm( 3123): VFY: unable to resolve virtual method 9862: Landroid/view/Window;.setStatusBarColor (I)V
D/dalvikvm( 3123): VFY: replacing opcode 0x6e at 0x0029
I/dalvikvm( 3123): Could not find method android.content.res.Resources.getDrawable, referenced from method android.support.v7.widget.u0.getDrawable
W/dalvikvm( 3123): VFY: unable to resolve virtual method 2845: Landroid/content/res/Resources;.getDrawable (ILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm( 3123): VFY: replacing opcode 0x6e at 0x0002
I/dalvikvm( 3123): Could not find method android.content.res.Resources.getDrawableForDensity, referenced from method android.support.v7.widget.u0.getDrawableForDensity
W/dalvikvm( 3123): VFY: unable to resolve virtual method 2847: Landroid/content/res/Resources;.getDrawableForDensity (IILandroid/content/res/Resources$Theme;)Landroid/graphics/drawable/Drawable;
D/dalvikvm( 3123): VFY: replacing opcode 0x6e at 0x0002
D/libEGL  ( 3123): loaded /system/lib/egl/libEGL_mali.so
D/libEGL  ( 3123): loaded /system/lib/egl/libGLESv1_CM_mali.so
D/libEGL  ( 3123): loaded /system/lib/egl/libGLESv2_mali.so
E/        ( 3123): Device driver API match
E/        ( 3123): Device driver API version: 23
E/        ( 3123): User space API version: 23 
E/        ( 3123): mali: REVISION=Linux-r3p2-01rel3 BUILD_DATE=Fri Mar 21 13:52:50 KST 2014 
D/OpenGLRenderer( 3123): Enabling debug mode 0
I/Timeline( 3123): Timeline: Activity_idle id: android.os.BinderProxy@41fcdee8 time:296034842
E/RenderScript_jni( 3123): Error loading RS jni library: java.lang.UnsatisfiedLinkError: XPrivacy
W/dalvikvm( 3123): threadid=12: thread exiting with uncaught exception (group=0x4171bce0)
--------- beginning of /dev/log/system
E/AndroidRuntime( 3123): FATAL EXCEPTION: CameraCallbackHandlerThread
E/AndroidRuntime( 3123): Process: de.markusfisch.android.binaryeye, PID: 3123
E/AndroidRuntime( 3123): android.support.v8.renderscript.RSRuntimeException: Error loading RS jni library: java.lang.UnsatisfiedLinkError: XPrivacy Support lib API: 2301
E/AndroidRuntime( 3123): 	at android.support.v8.renderscript.RenderScript.internalCreate()
E/AndroidRuntime( 3123): 	at android.support.v8.renderscript.RenderScript.create()
E/AndroidRuntime( 3123): 	at android.support.v8.renderscript.RenderScript.create()
E/AndroidRuntime( 3123): 	at android.support.v8.renderscript.RenderScript.create()
E/AndroidRuntime( 3123): 	at android.support.v8.renderscript.RenderScript.create()
E/AndroidRuntime( 3123): 	at c.a.a.a.h.a.<init>()
E/AndroidRuntime( 3123): 	at de.markusfisch.android.binaryeye.activity.CameraActivity.a()
E/AndroidRuntime( 3123): 	at de.markusfisch.android.binaryeye.activity.CameraActivity.a()
E/AndroidRuntime( 3123): 	at de.markusfisch.android.binaryeye.activity.CameraActivity$b$a.onPreviewFrame()
E/AndroidRuntime( 3123): 	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:981)
E/AndroidRuntime( 3123): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3123): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3123): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/System  ( 3123): Uncaught exception thrown by finalizer
E/System  ( 3123): android.support.v8.renderscript.RSInvalidStateException: Calling RS with no Context active.
E/System  ( 3123): 	at android.support.v8.renderscript.RenderScript.validate()
E/System  ( 3123): 	at android.support.v8.renderscript.RenderScript.nContextFinish()
E/System  ( 3123): 	at android.support.v8.renderscript.RenderScript.helpDestroy()
E/System  ( 3123): 	at android.support.v8.renderscript.RenderScript.finalize()
E/System  ( 3123): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
E/System  ( 3123): 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
E/System  ( 3123): 	at java.lang.Thread.run(Thread.java:841)
I/Process ( 3123): Sending signal. PID: 3123 SIG: 9

```

</details>

**Comment by markusfisch** [comment]
Yes, RenderScript is used for rotation of the camera frame, but also for downsampling the frame. Both operations don't require RenderScript, of course, but RenderScript is - at least in theory - the fastest way to perform these operations. In practice, performance can vary wildly because RenderScript is an abstraction that is executed either on CPU _or_ GPU depending on what's available on a device. And yes, it's run by native system libraries that also vary very much between vendors and versions.

So it's not an unencumbered choice for sure. At some point, I already made RenderScript optional (in a development build) because I was wrestling to get RenderScript to run on Lineage devices.

Also, RenderScript seems to not get much love from Google itself because building an App Bundle results in a corrupted build. Which is why Binary Eye is stuck with heavy APKs at the moment.

On the other hand, it's still the fastest option for _most_ devices. And I care for speed because the faster the camera image can be processed, the more images can be processed in a given time. And this means barcodes can be recognized faster just simply because there are more images to work with.

What makes things worse is that ZXing isn't exactly fast too. It's full of allocations in the hot path and it often transforms data when it would be faster to just read them with a different algorithm.

So dropping RenderScript would have some benefits but also some serious drawbacks. The only option I see is making it optional for devices where it doesn't run well. What would you think of a switch in the settings for this? Of course, Binary Eye would still include RenderScript libraries in that case.

**Comment by KOLANICH** [comment]
>RenderScript is an abstraction that is executed either on CPU or GPU depending on what's available on a device.

Thanks for the info. I have assummed that a GPU is always available.

>the only option I see is making it optional for devices where it doesn't run well. What would you think of a switch in the settings for this?

This was my fault. I have allowed loading libs but have not allowed `exec`. After I have allowed `exec` it runs fine.
